# Generated by Django 5.0.2 on 2024-02-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationdata',
            name='error_log',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='migrationdata',
            name='status_query',
            field=models.BooleanField(null=True),
        ),
    ]
