# Generated by Django 5.0.2 on 2024-05-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_migrationdata_sql_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationdata',
            name='sql_query',
            field=models.TextField(max_length=250),
        ),
    ]
