# Generated by Django 5.0.2 on 2024-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_migrationconfig_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repointegration',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
