# Generated by Django 5.0.2 on 2024-04-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_repointegration_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='migrationdata',
            old_name='author',
            new_name='engineer_name',
        ),
    ]
