# Generated by Django 5.0.2 on 2024-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_migrationdata_sql_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationconfig',
            name='db_password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
