# Generated by Django 5.0.2 on 2024-02-27 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_migrationdata_created_at_migrationdata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationdata',
            name='id_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repointegration'),
        ),
        migrations.CreateModel(
            name='migrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_location', models.CharField(max_length=20)),
                ('id_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repointegration')),
            ],
        ),
    ]
