# Generated by Django 5.0.2 on 2024-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_migrationconfig_db_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationconfig',
            name='db_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
