# Generated by Django 5.0.2 on 2024-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_migrationdata_id_repo_migrationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationconfig',
            name='db_host',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='migrationconfig',
            name='db_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='migrationconfig',
            name='db_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='migrationconfig',
            name='db_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
