# Generated by Django 5.0.2 on 2024-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_migrationconfig_db_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repointegration',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
