# Generated by Django 5.0.2 on 2024-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_migrationconfig_db_host_migrationconfig_db_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationdata',
            name='status_query',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
