# Generated by Django 5.0.2 on 2024-03-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_migrationdata_status_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationdata',
            name='batch_version',
        ),
    ]
