# Generated by Django 5.0.2 on 2024-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_repointegration_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationconfig',
            name='folder_location',
            field=models.CharField(max_length=50),
        ),
    ]
