# Generated by Django 5.0.2 on 2024-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_migrationconfig_db_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repointegration',
            name='token',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
